---
sudo: required
dist: trusty

language: c

compiler:
  - clang
  - gcc

env:
  matrix:
    - MAKE_TARGET=check
    - MAKE_TARGET=distcheck

matrix:
  include:
    - compiler: gcc
      env: MAKE_TARGET=lcov CONFIGURE_FLAGS=--enable-code-coverage

addons:
  apt:
    packages:
    - lcov
    - python-docutils

before_install:
  - git clone https://github.com/varnishcache/varnish-cache.git ./varnish
  - pushd varnish
  - ./autogen.sh
  - ./configure
  - make -sj32
  - sudo make PREFIX="/usr/local" install
  - sudo ldconfig
  - popd

before_script:
  - ./autogen.sh
  - ./configure --prefix=/usr $CONFIGURE_FLAGS
  - make -j4

script:
  - make $MAKE_TARGET -j1

after_success:
  - test "$MAKE_TARGET" = lcov || exit 0
  - cp libvmod-gossip-*-coverage.info codecov.info
  - bash <(curl -s https://codecov.io/bash) -X gcov -X coveragepy

after_failure:
  - |
    for log in $(find src/tests/ -name '*.log' | sort); do
      if grep -q ':test-result: FAIL' $(echo "$log" | sed 's/log$/trs/'); then
        printf "

    +==============================================================================+
    | %-76s |
    +==============================================================================+

    " "$log"
        cat "$log"
      fi
    done
